### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by emanxu** [antonio24073/aapanel#1]
May I see your Dockerfile, please? I would like to learn about your Dockerfile construction

**Comment by antonio24073** [comment]
![image](https://github.com/antonio24073/aapanel/assets/40250610/5740af41-f3c0-45c9-a3e8-987ab3675a23)

**Comment by emanxu** [comment]
thank you!!

**Comment by antonio24073** [comment]
Hi @PoorThatcher, 
I put the docker-file in the repository.. but I reduced the scope of the project.

**Comment by emanxu** [comment]
I see , thank you .
I just learn docker, you help me a lot .
